"use client";
import dynamic from "next/dynamic";
import { PreviewPane } from "@/components/preview/preview-pane";
interface Props { category: string; slug: string; }
const d: Record<string, Record<string, React.ComponentType>> = {
  "accordions": {
    "bordered-faq-accordion": dynamic(() => import("@/registry/accordions/bordered-faq-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "card-fold-accordion": dynamic(() => import("@/registry/accordions/card-fold-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "category-grid-accordion": dynamic(() => import("@/registry/accordions/category-grid-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "code-block-collapsible-accordion": dynamic(() => import("@/registry/accordions/code-block-collapsible-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-accordion": dynamic(() => import("@/registry/accordions/gradient-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "horizontal-split-accordion": dynamic(() => import("@/registry/accordions/horizontal-split-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-accordion": dynamic(() => import("@/registry/accordions/icon-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "multi-accordion": dynamic(() => import("@/registry/accordions/multi-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "multi-level-tree-accordion": dynamic(() => import("@/registry/accordions/multi-level-tree-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "nested-accordion": dynamic(() => import("@/registry/accordions/nested-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "numbered-step-guide-accordion": dynamic(() => import("@/registry/accordions/numbered-step-guide-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pill-expand-accordion": dynamic(() => import("@/registry/accordions/pill-expand-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "preview-card-accordion": dynamic(() => import("@/registry/accordions/preview-card-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "smooth-accordion": dynamic(() => import("@/registry/accordions/smooth-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stepped-form-accordion": dynamic(() => import("@/registry/accordions/stepped-form-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "timeline-step-accordion": dynamic(() => import("@/registry/accordions/timeline-step-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "tree-hierarchy-accordion": dynamic(() => import("@/registry/accordions/tree-hierarchy-accordion/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "alerts": {
    "action-alert": dynamic(() => import("@/registry/alerts/action-alert/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "animated-alert": dynamic(() => import("@/registry/alerts/animated-alert/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "announcement-top-bar": dynamic(() => import("@/registry/alerts/announcement-top-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "banner-alert": dynamic(() => import("@/registry/alerts/banner-alert/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "cookie-consent-alert": dynamic(() => import("@/registry/alerts/cookie-consent-alert/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "corner-popup-toast": dynamic(() => import("@/registry/alerts/corner-popup-toast/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "download-complete-toast": dynamic(() => import("@/registry/alerts/download-complete-toast/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "floating-toast": dynamic(() => import("@/registry/alerts/floating-toast/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-banner-notice": dynamic(() => import("@/registry/alerts/gradient-banner-notice/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "network-offline-banner": dynamic(() => import("@/registry/alerts/network-offline-banner/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "security-warning-badge": dynamic(() => import("@/registry/alerts/security-warning-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "session-timeout-alert": dynamic(() => import("@/registry/alerts/session-timeout-alert/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "system-status-banner": dynamic(() => import("@/registry/alerts/system-status-banner/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "toast-notification": dynamic(() => import("@/registry/alerts/toast-notification/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "trial-ending-callout": dynamic(() => import("@/registry/alerts/trial-ending-callout/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "unsaved-changes-banner": dynamic(() => import("@/registry/alerts/unsaved-changes-banner/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "update-ready-snackbar": dynamic(() => import("@/registry/alerts/update-ready-snackbar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "upgrade-pro-callout": dynamic(() => import("@/registry/alerts/upgrade-pro-callout/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "avatars": {
    "avatar-group": dynamic(() => import("@/registry/avatars/avatar-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "avatar-hover-card": dynamic(() => import("@/registry/avatars/avatar-hover-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "avatar-with-story-ring": dynamic(() => import("@/registry/avatars/avatar-with-story-ring/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bordered-avatar": dynamic(() => import("@/registry/avatars/bordered-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "cross-fade-status-avatar": dynamic(() => import("@/registry/avatars/cross-fade-status-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dual-user-overlap-avatar": dynamic(() => import("@/registry/avatars/dual-user-overlap-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-frame-avatar": dynamic(() => import("@/registry/avatars/gradient-frame-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "indicator-dot-avatar": dynamic(() => import("@/registry/avatars/indicator-dot-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "initial-avatar": dynamic(() => import("@/registry/avatars/initial-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "initials-color-avatar": dynamic(() => import("@/registry/avatars/initials-color-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "online-status-avatar": dynamic(() => import("@/registry/avatars/online-status-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pulse-ring-avatar": dynamic(() => import("@/registry/avatars/pulse-ring-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ring-avatar": dynamic(() => import("@/registry/avatars/ring-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "role-badge-avatar": dynamic(() => import("@/registry/avatars/role-badge-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stacked-avatars": dynamic(() => import("@/registry/avatars/stacked-avatars/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "status-avatar": dynamic(() => import("@/registry/avatars/status-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "team-cluster-avatar-group": dynamic(() => import("@/registry/avatars/team-cluster-avatar-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "team-count-cluster-avatar": dynamic(() => import("@/registry/avatars/team-count-cluster-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "verified-avatar": dynamic(() => import("@/registry/avatars/verified-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "backgrounds": {
    "aurora-background": dynamic(() => import("@/registry/backgrounds/aurora-background/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "circuit-board-pcb-bg": dynamic(() => import("@/registry/backgrounds/circuit-board-pcb-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dot-matrix-glow": dynamic(() => import("@/registry/backgrounds/dot-matrix-glow/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dot-pattern": dynamic(() => import("@/registry/backgrounds/dot-pattern/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "flicker-star-mesh": dynamic(() => import("@/registry/backgrounds/flicker-star-mesh/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-blob-bg": dynamic(() => import("@/registry/backgrounds/gradient-blob-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-mesh": dynamic(() => import("@/registry/backgrounds/gradient-mesh/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "grid-background": dynamic(() => import("@/registry/backgrounds/grid-background/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "hex-grid-bg": dynamic(() => import("@/registry/backgrounds/hex-grid-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "isometric-cube-grid": dynamic(() => import("@/registry/backgrounds/isometric-cube-grid/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "matrix-rain-canvas-bg": dynamic(() => import("@/registry/backgrounds/matrix-rain-canvas-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "moving-gradient-radial": dynamic(() => import("@/registry/backgrounds/moving-gradient-radial/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "noise-bg": dynamic(() => import("@/registry/backgrounds/noise-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "particles-background": dynamic(() => import("@/registry/backgrounds/particles-background/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "prism-light-leak-bg": dynamic(() => import("@/registry/backgrounds/prism-light-leak-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "retro-grid-wave": dynamic(() => import("@/registry/backgrounds/retro-grid-wave/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "starfield-bg": dynamic(() => import("@/registry/backgrounds/starfield-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "subtle-grain-mesh-bg": dynamic(() => import("@/registry/backgrounds/subtle-grain-mesh-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "topo-contour-lines-bg": dynamic(() => import("@/registry/backgrounds/topo-contour-lines-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "warp-speed-stars-bg": dynamic(() => import("@/registry/backgrounds/warp-speed-stars-bg/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "badges": {
    "active-indicator-badge": dynamic(() => import("@/registry/badges/active-indicator-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "animated-badge": dynamic(() => import("@/registry/badges/animated-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "badge-group": dynamic(() => import("@/registry/badges/badge-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "beta-access-badge": dynamic(() => import("@/registry/badges/beta-access-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "blinking-live-dot": dynamic(() => import("@/registry/badges/blinking-live-dot/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "count-badge": dynamic(() => import("@/registry/badges/count-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "free-tier-badge": dynamic(() => import("@/registry/badges/free-tier-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-badge": dynamic(() => import("@/registry/badges/gradient-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-pill-badge": dynamic(() => import("@/registry/badges/gradient-pill-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "hot-deal-badge": dynamic(() => import("@/registry/badges/hot-deal-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "notification-badge": dynamic(() => import("@/registry/badges/notification-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "number-pill-badge": dynamic(() => import("@/registry/badges/number-pill-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pill-counter-badge": dynamic(() => import("@/registry/badges/pill-counter-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ping-status-badge": dynamic(() => import("@/registry/badges/ping-status-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pulse-badge": dynamic(() => import("@/registry/badges/pulse-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "secure-ssl-badge": dynamic(() => import("@/registry/badges/secure-ssl-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sponsored-tag-badge": dynamic(() => import("@/registry/badges/sponsored-tag-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "status-badge": dynamic(() => import("@/registry/badges/status-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "streak-counter-badge": dynamic(() => import("@/registry/badges/streak-counter-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "verified-badge": dynamic(() => import("@/registry/badges/verified-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "version-release-badge": dynamic(() => import("@/registry/badges/version-release-badge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "breadcrumbs": {
    "animated-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/animated-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "chevron-flow-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/chevron-flow-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "chip-style-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/chip-style-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "collapsed-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/collapsed-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/icon-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-folder-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/icon-folder-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "minimal-dot-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/minimal-dot-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pill-step-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/pill-step-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slash-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/slash-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stepper-trail-breadcrumbs": dynamic(() => import("@/registry/breadcrumbs/stepper-trail-breadcrumbs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "buttons": {
    "3d-button": dynamic(() => import("@/registry/buttons/3d-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "border-beam-btn": dynamic(() => import("@/registry/buttons/border-beam-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bounce-button": dynamic(() => import("@/registry/buttons/bounce-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "confetti-button": dynamic(() => import("@/registry/buttons/confetti-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "copy-button": dynamic(() => import("@/registry/buttons/copy-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "cyber-glitch-btn": dynamic(() => import("@/registry/buttons/cyber-glitch-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dual-tone-gradient-btn": dynamic(() => import("@/registry/buttons/dual-tone-gradient-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "expand-icon-button": dynamic(() => import("@/registry/buttons/expand-icon-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glass-morphism-button": dynamic(() => import("@/registry/buttons/glass-morphism-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-border-pill-button": dynamic(() => import("@/registry/buttons/glow-border-pill-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-button": dynamic(() => import("@/registry/buttons/glow-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-border-button": dynamic(() => import("@/registry/buttons/gradient-border-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-button": dynamic(() => import("@/registry/buttons/gradient-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "haptic-bounce-press-btn": dynamic(() => import("@/registry/buttons/haptic-bounce-press-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "hologram-shimmer-btn": dynamic(() => import("@/registry/buttons/hologram-shimmer-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-button": dynamic(() => import("@/registry/buttons/icon-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "like-button": dynamic(() => import("@/registry/buttons/like-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "liquid-bubble-btn": dynamic(() => import("@/registry/buttons/liquid-bubble-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "loading-button": dynamic(() => import("@/registry/buttons/loading-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-button": dynamic(() => import("@/registry/buttons/magnetic-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-fill-btn": dynamic(() => import("@/registry/buttons/magnetic-fill-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-laser-sweep-btn": dynamic(() => import("@/registry/buttons/magnetic-laser-sweep-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "neon-button": dynamic(() => import("@/registry/buttons/neon-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "neon-cyber-pulse-btn": dynamic(() => import("@/registry/buttons/neon-cyber-pulse-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "outline-button": dynamic(() => import("@/registry/buttons/outline-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pulse-button": dynamic(() => import("@/registry/buttons/pulse-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pulse-ring-cta-button": dynamic(() => import("@/registry/buttons/pulse-ring-cta-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rainbow-glow-btn": dynamic(() => import("@/registry/buttons/rainbow-glow-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "retro-pixel-button": dynamic(() => import("@/registry/buttons/retro-pixel-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ripple-button": dynamic(() => import("@/registry/buttons/ripple-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "shimmer-button": dynamic(() => import("@/registry/buttons/shimmer-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "shimmer-sweep-pill-btn": dynamic(() => import("@/registry/buttons/shimmer-sweep-pill-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slide-arrow-button": dynamic(() => import("@/registry/buttons/slide-arrow-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "social-button": dynamic(() => import("@/registry/buttons/social-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sound-wave-btn": dynamic(() => import("@/registry/buttons/sound-wave-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "split-button": dynamic(() => import("@/registry/buttons/split-button/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "cards": {
    "3d-layer-card": dynamic(() => import("@/registry/cards/3d-layer-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "api-endpoint-card": dynamic(() => import("@/registry/cards/api-endpoint-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "article-snippet-card": dynamic(() => import("@/registry/cards/article-snippet-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "battery-status-device-card": dynamic(() => import("@/registry/cards/battery-status-device-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "code-snippet-card": dynamic(() => import("@/registry/cards/code-snippet-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "credit-card-preview": dynamic(() => import("@/registry/cards/credit-card-preview/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "feature-card": dynamic(() => import("@/registry/cards/feature-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "feature-comparison-mini-card": dynamic(() => import("@/registry/cards/feature-comparison-mini-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "flip-card": dynamic(() => import("@/registry/cards/flip-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "git-commit-card": dynamic(() => import("@/registry/cards/git-commit-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glass-card": dynamic(() => import("@/registry/cards/glass-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-contour-card": dynamic(() => import("@/registry/cards/glow-contour-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-gradient-outline-card": dynamic(() => import("@/registry/cards/glow-gradient-outline-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-card": dynamic(() => import("@/registry/cards/gradient-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "hover-reveal-card": dynamic(() => import("@/registry/cards/hover-reveal-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "interactive-poll-card": dynamic(() => import("@/registry/cards/interactive-poll-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "interactive-pricing-slider": dynamic(() => import("@/registry/cards/interactive-pricing-slider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "live-traffic-map-card": dynamic(() => import("@/registry/cards/live-traffic-map-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "metric-growth-card": dynamic(() => import("@/registry/cards/metric-growth-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "notification-card": dynamic(() => import("@/registry/cards/notification-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pricing-card": dynamic(() => import("@/registry/cards/pricing-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "profile-card": dynamic(() => import("@/registry/cards/profile-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "server-latency-card": dynamic(() => import("@/registry/cards/server-latency-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "social-proof-card": dynamic(() => import("@/registry/cards/social-proof-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "spotlight-card": dynamic(() => import("@/registry/cards/spotlight-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stacked-hover-card": dynamic(() => import("@/registry/cards/stacked-hover-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stats-card": dynamic(() => import("@/registry/cards/stats-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "testimonial-card": dynamic(() => import("@/registry/cards/testimonial-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "tilt-card": dynamic(() => import("@/registry/cards/tilt-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "user-testimonial-slider-card": dynamic(() => import("@/registry/cards/user-testimonial-slider-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "chips": {
    "action-pill-chip": dynamic(() => import("@/registry/chips/action-pill-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "avatar-chip": dynamic(() => import("@/registry/chips/avatar-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "category-badge-chip": dynamic(() => import("@/registry/chips/category-badge-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "color-chip": dynamic(() => import("@/registry/chips/color-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "color-swatch-chip": dynamic(() => import("@/registry/chips/color-swatch-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dismissible-filter-chip": dynamic(() => import("@/registry/chips/dismissible-filter-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "filter-chip": dynamic(() => import("@/registry/chips/filter-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "filter-multi-select-chip": dynamic(() => import("@/registry/chips/filter-multi-select-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-chip": dynamic(() => import("@/registry/chips/glow-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-pill-chip": dynamic(() => import("@/registry/chips/gradient-pill-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "language-locale-chip": dynamic(() => import("@/registry/chips/language-locale-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "price-discount-chip": dynamic(() => import("@/registry/chips/price-discount-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "removable-chip": dynamic(() => import("@/registry/chips/removable-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "select-tag-chip": dynamic(() => import("@/registry/chips/select-tag-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "status-chip": dynamic(() => import("@/registry/chips/status-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "status-indicator-pill-chip": dynamic(() => import("@/registry/chips/status-indicator-pill-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "tag-counter-chip": dynamic(() => import("@/registry/chips/tag-counter-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "verified-author-chip": dynamic(() => import("@/registry/chips/verified-author-chip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "counters": {
    "active-users-live-counter": dynamic(() => import("@/registry/counters/active-users-live-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "animated-counter": dynamic(() => import("@/registry/counters/animated-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "animated-crypto-ticker-counter": dynamic(() => import("@/registry/counters/animated-crypto-ticker-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "animated-digit-reel": dynamic(() => import("@/registry/counters/animated-digit-reel/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "circular-countdown-clock": dynamic(() => import("@/registry/counters/circular-countdown-clock/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "compact-metric-counter": dynamic(() => import("@/registry/counters/compact-metric-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "countdown-target-timer": dynamic(() => import("@/registry/counters/countdown-target-timer/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "digital-clock-counter": dynamic(() => import("@/registry/counters/digital-clock-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "flip-counter": dynamic(() => import("@/registry/counters/flip-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "metric-increase-counter": dynamic(() => import("@/registry/counters/metric-increase-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "odometer-counter": dynamic(() => import("@/registry/counters/odometer-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "percentage-circle-counter": dynamic(() => import("@/registry/counters/percentage-circle-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "progress-counter": dynamic(() => import("@/registry/counters/progress-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rolling-number-ticker-counter": dynamic(() => import("@/registry/counters/rolling-number-ticker-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "score-multiplier-counter": dynamic(() => import("@/registry/counters/score-multiplier-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "step-milestone-counter": dynamic(() => import("@/registry/counters/step-milestone-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "timer-counter": dynamic(() => import("@/registry/counters/timer-counter/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "cursors": {
    "crosshair-precision-cursor": dynamic(() => import("@/registry/cursors/crosshair-precision-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "crosshair-target-cursor": dynamic(() => import("@/registry/cursors/crosshair-target-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-spotlight-reveal-cursor": dynamic(() => import("@/registry/cursors/glow-spotlight-reveal-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-trail-cursor": dynamic(() => import("@/registry/cursors/gradient-trail-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-bubble-cursor": dynamic(() => import("@/registry/cursors/magnetic-bubble-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-cursor": dynamic(() => import("@/registry/cursors/magnetic-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "magnetic-link-cursor": dynamic(() => import("@/registry/cursors/magnetic-link-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ring-cursor": dynamic(() => import("@/registry/cursors/ring-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "smooth-dot-follower-cursor": dynamic(() => import("@/registry/cursors/smooth-dot-follower-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "spotlight-cursor": dynamic(() => import("@/registry/cursors/spotlight-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "trail-cursor": dynamic(() => import("@/registry/cursors/trail-cursor/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "dividers": {
    "badge-centered-divider": dynamic(() => import("@/registry/dividers/badge-centered-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "code-comment-divider": dynamic(() => import("@/registry/dividers/code-comment-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "curved-separator-line": dynamic(() => import("@/registry/dividers/curved-separator-line/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dashed-border-divider": dynamic(() => import("@/registry/dividers/dashed-border-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dot-divider": dynamic(() => import("@/registry/dividers/dot-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "double-hairline-divider": dynamic(() => import("@/registry/dividers/double-hairline-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "double-line-accent-divider": dynamic(() => import("@/registry/dividers/double-line-accent-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-line-divider": dynamic(() => import("@/registry/dividers/glow-line-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glowing-orb-separator": dynamic(() => import("@/registry/dividers/glowing-orb-separator/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-divider": dynamic(() => import("@/registry/dividers/gradient-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-fade-divider": dynamic(() => import("@/registry/dividers/gradient-fade-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-laser-divider": dynamic(() => import("@/registry/dividers/gradient-laser-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-divider": dynamic(() => import("@/registry/dividers/icon-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "star-cluster-divider": dynamic(() => import("@/registry/dividers/star-cluster-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "text-divider": dynamic(() => import("@/registry/dividers/text-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "vertical-separator": dynamic(() => import("@/registry/dividers/vertical-separator/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "wave-divider": dynamic(() => import("@/registry/dividers/wave-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "zigzag-pattern-divider": dynamic(() => import("@/registry/dividers/zigzag-pattern-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "zigzag-sawtooth-divider": dynamic(() => import("@/registry/dividers/zigzag-sawtooth-divider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "inputs": {
    "animated-border-input": dynamic(() => import("@/registry/inputs/animated-border-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "character-countdown-input": dynamic(() => import("@/registry/inputs/character-countdown-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "character-limit-input": dynamic(() => import("@/registry/inputs/character-limit-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "color-palette-picker": dynamic(() => import("@/registry/inputs/color-palette-picker/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "color-picker": dynamic(() => import("@/registry/inputs/color-picker/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "copyable-snippet-input": dynamic(() => import("@/registry/inputs/copyable-snippet-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "credit-expiry-input": dynamic(() => import("@/registry/inputs/credit-expiry-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "credit-security-cvv-input": dynamic(() => import("@/registry/inputs/credit-security-cvv-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "currency-input": dynamic(() => import("@/registry/inputs/currency-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "file-dropzone": dynamic(() => import("@/registry/inputs/file-dropzone/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "floating-input": dynamic(() => import("@/registry/inputs/floating-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "floating-label-input": dynamic(() => import("@/registry/inputs/floating-label-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-prefix-input": dynamic(() => import("@/registry/inputs/icon-prefix-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "inline-edit-input": dynamic(() => import("@/registry/inputs/inline-edit-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "number-input": dynamic(() => import("@/registry/inputs/number-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "otp-input": dynamic(() => import("@/registry/inputs/otp-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "password-input": dynamic(() => import("@/registry/inputs/password-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pill-search-bar-input": dynamic(() => import("@/registry/inputs/pill-search-bar-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pin-input": dynamic(() => import("@/registry/inputs/pin-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "range-slider": dynamic(() => import("@/registry/inputs/range-slider/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "search-clear-input": dynamic(() => import("@/registry/inputs/search-clear-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "search-filter-input": dynamic(() => import("@/registry/inputs/search-filter-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "search-input": dynamic(() => import("@/registry/inputs/search-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "select-input": dynamic(() => import("@/registry/inputs/select-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stepper-quantity-input": dynamic(() => import("@/registry/inputs/stepper-quantity-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "tag-input": dynamic(() => import("@/registry/inputs/tag-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "textarea-auto": dynamic(() => import("@/registry/inputs/textarea-auto/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "verification-code-group": dynamic(() => import("@/registry/inputs/verification-code-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "voice-search-input": dynamic(() => import("@/registry/inputs/voice-search-input/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "kbd": {
    "arrow-cluster-nav-kbd": dynamic(() => import("@/registry/kbd/arrow-cluster-nav-kbd/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "caps-lock-indicator": dynamic(() => import("@/registry/kbd/caps-lock-indicator/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "combo-sequence-pill-kbd": dynamic(() => import("@/registry/kbd/combo-sequence-pill-kbd/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "command-palette-kbd": dynamic(() => import("@/registry/kbd/command-palette-kbd/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "function-keys-row-kbd": dynamic(() => import("@/registry/kbd/function-keys-row-kbd/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glow-keyboard-shortcut": dynamic(() => import("@/registry/kbd/glow-keyboard-shortcut/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "key-combo": dynamic(() => import("@/registry/kbd/key-combo/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "keyboard-key": dynamic(() => import("@/registry/kbd/keyboard-key/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "macro-key-pad": dynamic(() => import("@/registry/kbd/macro-key-pad/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "shortcut-display": dynamic(() => import("@/registry/kbd/shortcut-display/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "split-modifier-kbd": dynamic(() => import("@/registry/kbd/split-modifier-kbd/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "loaders": {
    "bar-cascade-wave-loader": dynamic(() => import("@/registry/loaders/bar-cascade-wave-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bar-loader": dynamic(() => import("@/registry/loaders/bar-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bouncing-cubes-loader": dynamic(() => import("@/registry/loaders/bouncing-cubes-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "clock-loader": dynamic(() => import("@/registry/loaders/clock-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "cube-rotate-loader": dynamic(() => import("@/registry/loaders/cube-rotate-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dna-spinner-loader": dynamic(() => import("@/registry/loaders/dna-spinner-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dots-grid": dynamic(() => import("@/registry/loaders/dots-grid/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dual-ring-spinner": dynamic(() => import("@/registry/loaders/dual-ring-spinner/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "equalizer-bars-loader": dynamic(() => import("@/registry/loaders/equalizer-bars-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "infinity-loop-loader": dynamic(() => import("@/registry/loaders/infinity-loop-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "laser-line-loader": dynamic(() => import("@/registry/loaders/laser-line-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "liquid-drop-loader": dynamic(() => import("@/registry/loaders/liquid-drop-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "orbit-loader": dynamic(() => import("@/registry/loaders/orbit-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "orbiting-electrons-loader": dynamic(() => import("@/registry/loaders/orbiting-electrons-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "progress-loader": dynamic(() => import("@/registry/loaders/progress-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pulse-dots": dynamic(() => import("@/registry/loaders/pulse-dots/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "quantum-orbit-loader": dynamic(() => import("@/registry/loaders/quantum-orbit-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "radar-sweep-loader": dynamic(() => import("@/registry/loaders/radar-sweep-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ring-pulse-loader": dynamic(() => import("@/registry/loaders/ring-pulse-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-shimmer": dynamic(() => import("@/registry/loaders/skeleton-shimmer/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "spinner-loader": dynamic(() => import("@/registry/loaders/spinner-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "typing-loader": dynamic(() => import("@/registry/loaders/typing-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "wave-loader": dynamic(() => import("@/registry/loaders/wave-loader/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "marquee": {
    "breaking-news-ticker-marquee": dynamic(() => import("@/registry/marquee/breaking-news-ticker-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "crypto-price-marquee": dynamic(() => import("@/registry/marquee/crypto-price-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "feature-grid-marquee": dynamic(() => import("@/registry/marquee/feature-grid-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "github-stargazers-marquee": dynamic(() => import("@/registry/marquee/github-stargazers-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-marquee": dynamic(() => import("@/registry/marquee/gradient-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-stream-marquee": dynamic(() => import("@/registry/marquee/icon-stream-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "infinite-marquee": dynamic(() => import("@/registry/marquee/infinite-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "logo-cloud-marquee": dynamic(() => import("@/registry/marquee/logo-cloud-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "logo-marquee": dynamic(() => import("@/registry/marquee/logo-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "metric-stats-ticker": dynamic(() => import("@/registry/marquee/metric-stats-ticker/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "partner-logos-marquee": dynamic(() => import("@/registry/marquee/partner-logos-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "reverse-ticker-marquee": dynamic(() => import("@/registry/marquee/reverse-ticker-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sponsor-wall-marquee": dynamic(() => import("@/registry/marquee/sponsor-wall-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "testimonial-marquee": dynamic(() => import("@/registry/marquee/testimonial-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "testimonial-quotes-marquee": dynamic(() => import("@/registry/marquee/testimonial-quotes-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "vertical-marquee": dynamic(() => import("@/registry/marquee/vertical-marquee/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "modals": {
    "auth-login-dialog": dynamic(() => import("@/registry/modals/auth-login-dialog/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bottom-sheet-mobile-modal": dynamic(() => import("@/registry/modals/bottom-sheet-mobile-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "command-search-modal": dynamic(() => import("@/registry/modals/command-search-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "confirm-dialog": dynamic(() => import("@/registry/modals/confirm-dialog/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "confirmation-prompt-modal": dynamic(() => import("@/registry/modals/confirmation-prompt-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "cookie-settings-modal": dynamic(() => import("@/registry/modals/cookie-settings-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "feedback-survey-modal": dynamic(() => import("@/registry/modals/feedback-survey-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "fullscreen-dialog": dynamic(() => import("@/registry/modals/fullscreen-dialog/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "media-gallery-lightbox": dynamic(() => import("@/registry/modals/media-gallery-lightbox/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "nested-sheet": dynamic(() => import("@/registry/modals/nested-sheet/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "quick-feedback-modal": dynamic(() => import("@/registry/modals/quick-feedback-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scale-modal": dynamic(() => import("@/registry/modals/scale-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "share-link-dialog": dynamic(() => import("@/registry/modals/share-link-dialog/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slide-drawer": dynamic(() => import("@/registry/modals/slide-drawer/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slide-in-sheet-modal": dynamic(() => import("@/registry/modals/slide-in-sheet-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "video-preview-modal": dynamic(() => import("@/registry/modals/video-preview-modal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "pagination": {
    "arrow-counter-pagination": dynamic(() => import("@/registry/pagination/arrow-counter-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bubble-page-selector": dynamic(() => import("@/registry/pagination/bubble-page-selector/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "compact-pagination": dynamic(() => import("@/registry/pagination/compact-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dot-pagination": dynamic(() => import("@/registry/pagination/dot-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "dot-slider-pagination": dynamic(() => import("@/registry/pagination/dot-slider-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "jump-pagination": dynamic(() => import("@/registry/pagination/jump-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "minimal-arrow-pagination": dynamic(() => import("@/registry/pagination/minimal-arrow-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "number-pagination": dynamic(() => import("@/registry/pagination/number-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "range-pagination": dynamic(() => import("@/registry/pagination/range-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slider-page-navigator": dynamic(() => import("@/registry/pagination/slider-page-navigator/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "stepper-pill-pagination": dynamic(() => import("@/registry/pagination/stepper-pill-pagination/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "progress": {
    "battery-cell-progress-bar": dynamic(() => import("@/registry/progress/battery-cell-progress-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "battery-level-gauge": dynamic(() => import("@/registry/progress/battery-level-gauge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "circular-progress": dynamic(() => import("@/registry/progress/circular-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "circular-timer-gauge": dynamic(() => import("@/registry/progress/circular-timer-gauge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-bar": dynamic(() => import("@/registry/progress/gradient-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-fill-progress-bar": dynamic(() => import("@/registry/progress/gradient-fill-progress-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-wave-progress": dynamic(() => import("@/registry/progress/gradient-wave-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "liquid-fill-gauge": dynamic(() => import("@/registry/progress/liquid-fill-gauge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "milestone-track-progress": dynamic(() => import("@/registry/progress/milestone-track-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "multi-segment-bar": dynamic(() => import("@/registry/progress/multi-segment-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "radial-progress": dynamic(() => import("@/registry/progress/radial-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "semicircle-gauge": dynamic(() => import("@/registry/progress/semicircle-gauge/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "step-checkpoint-bar": dynamic(() => import("@/registry/progress/step-checkpoint-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "step-milestone-progress-bar": dynamic(() => import("@/registry/progress/step-milestone-progress-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "steps-progress": dynamic(() => import("@/registry/progress/steps-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "striped-animated-progress": dynamic(() => import("@/registry/progress/striped-animated-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "ratings": {
    "bar-rating-distribution": dynamic(() => import("@/registry/ratings/bar-rating-distribution/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "custom-emoji-picker": dynamic(() => import("@/registry/ratings/custom-emoji-picker/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "emoji-rating": dynamic(() => import("@/registry/ratings/emoji-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "half-star-rating": dynamic(() => import("@/registry/ratings/half-star-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "heart-rating": dynamic(() => import("@/registry/ratings/heart-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "interactive-star-picker-rating": dynamic(() => import("@/registry/ratings/interactive-star-picker-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "like-dislike-pill": dynamic(() => import("@/registry/ratings/like-dislike-pill/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "nps-score-slider-rating": dynamic(() => import("@/registry/ratings/nps-score-slider-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "percentage-score-bar": dynamic(() => import("@/registry/ratings/percentage-score-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "reaction-picker-bar": dynamic(() => import("@/registry/ratings/reaction-picker-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sentiment-emoji-reaction-rating": dynamic(() => import("@/registry/ratings/sentiment-emoji-reaction-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "simple-badge-rating": dynamic(() => import("@/registry/ratings/simple-badge-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slider-rating": dynamic(() => import("@/registry/ratings/slider-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slider-score-rating": dynamic(() => import("@/registry/ratings/slider-score-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "star-rating": dynamic(() => import("@/registry/ratings/star-rating/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "thumb-feedback": dynamic(() => import("@/registry/ratings/thumb-feedback/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "scroll": {
    "back-to-top-pill": dynamic(() => import("@/registry/scroll/back-to-top-pill/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "count-up": dynamic(() => import("@/registry/scroll/count-up/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "fade-in-scroll": dynamic(() => import("@/registry/scroll/fade-in-scroll/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "floating-jump-to-top-btn": dynamic(() => import("@/registry/scroll/floating-jump-to-top-btn/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "horizontal-smooth-scroll": dynamic(() => import("@/registry/scroll/horizontal-smooth-scroll/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "infinite-virtual-list": dynamic(() => import("@/registry/scroll/infinite-virtual-list/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "parallax-image-card": dynamic(() => import("@/registry/scroll/parallax-image-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "parallax-text": dynamic(() => import("@/registry/scroll/parallax-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "reading-progress-top-bar": dynamic(() => import("@/registry/scroll/reading-progress-top-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "reveal-on-scroll": dynamic(() => import("@/registry/scroll/reveal-on-scroll/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-blur-header": dynamic(() => import("@/registry/scroll/scroll-blur-header/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-fade-in-section": dynamic(() => import("@/registry/scroll/scroll-fade-in-section/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-indicator-bar": dynamic(() => import("@/registry/scroll/scroll-indicator-bar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-progress": dynamic(() => import("@/registry/scroll/scroll-progress/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-snap-carousel": dynamic(() => import("@/registry/scroll/scroll-snap-carousel/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scroll-to-top": dynamic(() => import("@/registry/scroll/scroll-to-top/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "split-screen-parallax": dynamic(() => import("@/registry/scroll/split-screen-parallax/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sticky-chapter-sidebar": dynamic(() => import("@/registry/scroll/sticky-chapter-sidebar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sticky-nav-scroll": dynamic(() => import("@/registry/scroll/sticky-nav-scroll/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "skeletons": {
    "dashboard-widget-skeleton-card": dynamic(() => import("@/registry/skeletons/dashboard-widget-skeleton-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "post-feed-skeleton-card": dynamic(() => import("@/registry/skeletons/post-feed-skeleton-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-avatar": dynamic(() => import("@/registry/skeletons/skeleton-avatar/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-card": dynamic(() => import("@/registry/skeletons/skeleton-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-chat-bubbles": dynamic(() => import("@/registry/skeletons/skeleton-chat-bubbles/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-comment-thread": dynamic(() => import("@/registry/skeletons/skeleton-comment-thread/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-dashboard": dynamic(() => import("@/registry/skeletons/skeleton-dashboard/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-kanban-board": dynamic(() => import("@/registry/skeletons/skeleton-kanban-board/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-list": dynamic(() => import("@/registry/skeletons/skeleton-list/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-media-feed": dynamic(() => import("@/registry/skeletons/skeleton-media-feed/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-pricing-tier": dynamic(() => import("@/registry/skeletons/skeleton-pricing-tier/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-profile-header": dynamic(() => import("@/registry/skeletons/skeleton-profile-header/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-stats-grid": dynamic(() => import("@/registry/skeletons/skeleton-stats-grid/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-table": dynamic(() => import("@/registry/skeletons/skeleton-table/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-text": dynamic(() => import("@/registry/skeletons/skeleton-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "skeleton-video-player": dynamic(() => import("@/registry/skeletons/skeleton-video-player/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "user-profile-skeleton-card": dynamic(() => import("@/registry/skeletons/user-profile-skeleton-card/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "switches": {
    "compact-thumb-switch": dynamic(() => import("@/registry/switches/compact-thumb-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-segmented-switch": dynamic(() => import("@/registry/switches/icon-segmented-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-toggle-switch": dynamic(() => import("@/registry/switches/icon-toggle-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "ios-switch": dynamic(() => import("@/registry/switches/ios-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "labeled-switch": dynamic(() => import("@/registry/switches/labeled-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "neon-switch": dynamic(() => import("@/registry/switches/neon-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "slider-toggle-switch": dynamic(() => import("@/registry/switches/slider-toggle-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "status-label-switch": dynamic(() => import("@/registry/switches/status-label-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "theme-switch": dynamic(() => import("@/registry/switches/theme-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "volume-step-switch": dynamic(() => import("@/registry/switches/volume-step-switch/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "tabs": {
    "animated-tabs": dynamic(() => import("@/registry/tabs/animated-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "badge-pill-tabs": dynamic(() => import("@/registry/tabs/badge-pill-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bubble-tabs": dynamic(() => import("@/registry/tabs/bubble-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "floating-dock-tabs": dynamic(() => import("@/registry/tabs/floating-dock-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "folder-index-tabs": dynamic(() => import("@/registry/tabs/folder-index-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "folder-tab-group": dynamic(() => import("@/registry/tabs/folder-tab-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glass-dock-tabs": dynamic(() => import("@/registry/tabs/glass-dock-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-grid-tabs": dynamic(() => import("@/registry/tabs/icon-grid-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-labeled-dock-tabs": dynamic(() => import("@/registry/tabs/icon-labeled-dock-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-tabs": dynamic(() => import("@/registry/tabs/icon-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "minimal-line-tabs": dynamic(() => import("@/registry/tabs/minimal-line-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pill-tabs": dynamic(() => import("@/registry/tabs/pill-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sliding-pill-indicator-tabs": dynamic(() => import("@/registry/tabs/sliding-pill-indicator-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "sliding-pill-tabs": dynamic(() => import("@/registry/tabs/sliding-pill-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "tag-filter-tabs": dynamic(() => import("@/registry/tabs/tag-filter-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "underline-tabs": dynamic(() => import("@/registry/tabs/underline-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "vertical-nav-tabs": dynamic(() => import("@/registry/tabs/vertical-nav-tabs/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "text-animations": {
    "blur-focus-text": dynamic(() => import("@/registry/text-animations/blur-focus-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "blur-reveal-text": dynamic(() => import("@/registry/text-animations/blur-reveal-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "blur-slide-reveal": dynamic(() => import("@/registry/text-animations/blur-slide-reveal/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "blur-unmask-reveal-text": dynamic(() => import("@/registry/text-animations/blur-unmask-reveal-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "counter-text": dynamic(() => import("@/registry/text-animations/counter-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "curved-text": dynamic(() => import("@/registry/text-animations/curved-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "drop-shadow-pop-text": dynamic(() => import("@/registry/text-animations/drop-shadow-pop-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "fade-words": dynamic(() => import("@/registry/text-animations/fade-words/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "flip-words": dynamic(() => import("@/registry/text-animations/flip-words/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "glitch-text": dynamic(() => import("@/registry/text-animations/glitch-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-text": dynamic(() => import("@/registry/text-animations/gradient-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-wave-text": dynamic(() => import("@/registry/text-animations/gradient-wave-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "highlight-text": dynamic(() => import("@/registry/text-animations/highlight-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "laser-beam-reveal-text": dynamic(() => import("@/registry/text-animations/laser-beam-reveal-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "matrix-code-rain": dynamic(() => import("@/registry/text-animations/matrix-code-rain/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "neon-flicker-text": dynamic(() => import("@/registry/text-animations/neon-flicker-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rainbow-wave-animated-text": dynamic(() => import("@/registry/text-animations/rainbow-wave-animated-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rotating-word-text": dynamic(() => import("@/registry/text-animations/rotating-word-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "scramble-text": dynamic(() => import("@/registry/text-animations/scramble-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "shimmer-gradient-text": dynamic(() => import("@/registry/text-animations/shimmer-gradient-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "typewriter-text": dynamic(() => import("@/registry/text-animations/typewriter-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "typewriter-word-cycling-text": dynamic(() => import("@/registry/text-animations/typewriter-word-cycling-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "typing-delete": dynamic(() => import("@/registry/text-animations/typing-delete/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "vintage-terminal-typing": dynamic(() => import("@/registry/text-animations/vintage-terminal-typing/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "wave-text": dynamic(() => import("@/registry/text-animations/wave-text/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "timeline": {
    "activity-feed": dynamic(() => import("@/registry/timeline/activity-feed/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "delivery-tracking-timeline": dynamic(() => import("@/registry/timeline/delivery-tracking-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "git-branch-timeline": dynamic(() => import("@/registry/timeline/git-branch-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "git-commit-history-timeline": dynamic(() => import("@/registry/timeline/git-commit-history-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "horizontal-timeline": dynamic(() => import("@/registry/timeline/horizontal-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "milestone-card-timeline": dynamic(() => import("@/registry/timeline/milestone-card-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "roadmap-quarterly-timeline": dynamic(() => import("@/registry/timeline/roadmap-quarterly-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "step-timeline": dynamic(() => import("@/registry/timeline/step-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "version-history-timeline": dynamic(() => import("@/registry/timeline/version-history-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "vertical-timeline": dynamic(() => import("@/registry/timeline/vertical-timeline/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "toggles": {
    "airplane-mode-toggle": dynamic(() => import("@/registry/toggles/airplane-mode-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "audio-mute-toggle": dynamic(() => import("@/registry/toggles/audio-mute-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "bookmark-save-toggle": dynamic(() => import("@/registry/toggles/bookmark-save-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "checkbox-badge-toggle": dynamic(() => import("@/registry/toggles/checkbox-badge-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "checkbox-toggle": dynamic(() => import("@/registry/toggles/checkbox-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "day-night-toggle": dynamic(() => import("@/registry/toggles/day-night-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "expand-drawer-toggle": dynamic(() => import("@/registry/toggles/expand-drawer-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "icon-toggle": dynamic(() => import("@/registry/toggles/icon-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "liquid-toggle": dynamic(() => import("@/registry/toggles/liquid-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "lock-toggle": dynamic(() => import("@/registry/toggles/lock-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "multi-state-toggle": dynamic(() => import("@/registry/toggles/multi-state-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "pin-action-toggle": dynamic(() => import("@/registry/toggles/pin-action-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "power-toggle": dynamic(() => import("@/registry/toggles/power-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "radio-group": dynamic(() => import("@/registry/toggles/radio-group/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "star-favorite-toggle": dynamic(() => import("@/registry/toggles/star-favorite-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "theme-slider-toggle": dynamic(() => import("@/registry/toggles/theme-slider-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "visibility-eye-toggle": dynamic(() => import("@/registry/toggles/visibility-eye-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "wifi-signal-toggle": dynamic(() => import("@/registry/toggles/wifi-signal-toggle/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
  "tooltips": {
    "animated-tooltip": dynamic(() => import("@/registry/tooltips/animated-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "avatar-preview-tooltip": dynamic(() => import("@/registry/tooltips/avatar-preview-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "badge-status-callout-tooltip": dynamic(() => import("@/registry/tooltips/badge-status-callout-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "copy-code-tooltip": dynamic(() => import("@/registry/tooltips/copy-code-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "gradient-tooltip": dynamic(() => import("@/registry/tooltips/gradient-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "interactive-tooltip": dynamic(() => import("@/registry/tooltips/interactive-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "keyboard-shortcut-hint-tooltip": dynamic(() => import("@/registry/tooltips/keyboard-shortcut-hint-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rich-media-preview-tooltip": dynamic(() => import("@/registry/tooltips/rich-media-preview-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "rich-preview-tooltip": dynamic(() => import("@/registry/tooltips/rich-preview-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
    "shortcut-badge-tooltip": dynamic(() => import("@/registry/tooltips/shortcut-badge-tooltip/demo").then((m) => ({ default: m.Demo })), { ssr: false }),
  },
};
export function ComponentDetailClient({ category, slug }: Props) {
  const C = d[category]?.[slug];
  return <PreviewPane>{C ? <C /> : <div className="text-[var(--muted-foreground)] text-sm italic">Preview not available</div>}</PreviewPane>;
}
